name: fitflow_gym
description: Offline-first white-label gym manager (autobuild repo)
publish_to: "none"
version: 0.2.2+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_local_notifications: ^17.2.3
  workmanager: ^0.9.0+3
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  mobile_scanner: ^7.0.1
  json_annotation: ^4.9.0
  pdf: ^3.11.1
  printing: ^5.13.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.png
